### ISSUE TITLE
Auto-generate documentation on each push

### ISSUE THREAD

**Issue by JoshuaDRose** [JoshuaDRose/taskify#4]
### Changes
* use sphinx to auto-gen documentation
* documentation should be living in `docs/`

#### TODO

- [x] Add sphinx to `requirements-dev.txt`
- [ ] Create `docs/`
- [ ] Run `sphinx-quickstart` in `docs/`
- [ ] configure `docs/config.py`
